# Use GitHub Pages' default theme
theme: jekyll-theme-primer

# Enable GitHub Pages settings
baseurl: "/E21-F25"   # Important for project site URLs
url: "https://emadmasroor.github.io"

# Markdown settings
markdown: kramdown
kramdown:
  auto_ids: true       # Generate IDs for headings automatically
  toc_levels: 1..3     # Include h1, h2, h3 in TOC

# Optional: site title
title: ENGR 21 Fall 2025
